[package]
name = "safe_files"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10"
base64 = "0.21"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"
ctrlc = "3.4"
walkdir = "2.3"
dotenv = "0.15"
sha2 = "0.10.9"
